//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace tests {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class RegionDataSet : DataSet {
        
        private RegionDataTable tableRegion;
        
        public RegionDataSet() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected RegionDataSet(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Region"] != null)) {
                    this.Tables.Add(new RegionDataTable(ds.Tables["Region"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RegionDataTable Region {
            get {
                return this.tableRegion;
            }
        }
        
        public override DataSet Clone() {
            RegionDataSet cln = ((RegionDataSet)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Region"] != null)) {
                this.Tables.Add(new RegionDataTable(ds.Tables["Region"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableRegion = ((RegionDataTable)(this.Tables["Region"]));
            if ((this.tableRegion != null)) {
                this.tableRegion.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "RegionDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/RegionDataSet.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableRegion = new RegionDataTable();
            this.Tables.Add(this.tableRegion);
        }
        
        private bool ShouldSerializeRegion() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void RegionRowChangeEventHandler(object sender, RegionRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RegionDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnRegionID;
            
            private DataColumn columnRegionDescription;
            
            internal RegionDataTable() : 
                    base("Region") {
                this.InitClass();
            }
            
            internal RegionDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn RegionIDColumn {
                get {
                    return this.columnRegionID;
                }
            }
            
            internal DataColumn RegionDescriptionColumn {
                get {
                    return this.columnRegionDescription;
                }
            }
            
            public RegionRow this[int index] {
                get {
                    return ((RegionRow)(this.Rows[index]));
                }
            }
            
            public event RegionRowChangeEventHandler RegionRowChanged;
            
            public event RegionRowChangeEventHandler RegionRowChanging;
            
            public event RegionRowChangeEventHandler RegionRowDeleted;
            
            public event RegionRowChangeEventHandler RegionRowDeleting;
            
            public void AddRegionRow(RegionRow row) {
                this.Rows.Add(row);
            }
            
            public RegionRow AddRegionRow(int RegionID, string RegionDescription) {
                RegionRow rowRegionRow = ((RegionRow)(this.NewRow()));
                rowRegionRow.ItemArray = new object[] {
                        RegionID,
                        RegionDescription};
                this.Rows.Add(rowRegionRow);
                return rowRegionRow;
            }
            
            public RegionRow FindByRegionID(int RegionID) {
                return ((RegionRow)(this.Rows.Find(new object[] {
                            RegionID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                RegionDataTable cln = ((RegionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new RegionDataTable();
            }
            
            internal void InitVars() {
                this.columnRegionID = this.Columns["RegionID"];
                this.columnRegionDescription = this.Columns["RegionDescription"];
            }
            
            private void InitClass() {
                this.columnRegionID = new DataColumn("RegionID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegionID);
                this.columnRegionDescription = new DataColumn("RegionDescription", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegionDescription);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnRegionID}, true));
                this.columnRegionID.AllowDBNull = false;
                this.columnRegionID.Unique = true;
                this.columnRegionDescription.AllowDBNull = false;
            }
            
            public RegionRow NewRegionRow() {
                return ((RegionRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new RegionRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(RegionRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RegionRowChanged != null)) {
                    this.RegionRowChanged(this, new RegionRowChangeEvent(((RegionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RegionRowChanging != null)) {
                    this.RegionRowChanging(this, new RegionRowChangeEvent(((RegionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RegionRowDeleted != null)) {
                    this.RegionRowDeleted(this, new RegionRowChangeEvent(((RegionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RegionRowDeleting != null)) {
                    this.RegionRowDeleting(this, new RegionRowChangeEvent(((RegionRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveRegionRow(RegionRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RegionRow : DataRow {
            
            private RegionDataTable tableRegion;
            
            internal RegionRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableRegion = ((RegionDataTable)(this.Table));
            }
            
            public int RegionID {
                get {
                    return ((int)(this[this.tableRegion.RegionIDColumn]));
                }
                set {
                    this[this.tableRegion.RegionIDColumn] = value;
                }
            }
            
            public string RegionDescription {
                get {
                    return ((string)(this[this.tableRegion.RegionDescriptionColumn]));
                }
                set {
                    this[this.tableRegion.RegionDescriptionColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RegionRowChangeEvent : EventArgs {
            
            private RegionRow eventRow;
            
            private DataRowAction eventAction;
            
            public RegionRowChangeEvent(RegionRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public RegionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
