APP=Converter

sources = \
	Converter.cs

all: test

test: $(sources)
	rm -Rf $(APP).app
	mcs -debug $(sources) -out:$(APP).exe -r:System.Drawing -r:System.Windows.Forms -r:System.Data
	macpack -n:$(APP) -a:./$(APP).exe -m:1 -o:. -r:mono.icns
	cp ./Info.plist $(APP).app/Contents/Info.plist

run: test
	./$(APP)/Contents/MacOS/$(APP)

