Literal float tokens as generated by monodis like "1e+150" fail to be parsed by
ilasm as NumberHelper only checks for a '.' to consider a number a float.
Quick hack fix of having it also check for an 'e' or 'E'.

- Steven Brown <swbrown@ucsd.edu>


Index: ilasm/scanner/NumberHelper.cs
===================================================================
RCS file: /mono/mcs/ilasm/scanner/NumberHelper.cs,v
retrieving revision 1.8
diff -u -r1.8 NumberHelper.cs
--- ilasm/scanner/NumberHelper.cs	10 Jun 2004 21:01:19 -0000	1.8
+++ ilasm/scanner/NumberHelper.cs	29 Jun 2004 06:00:00 -0000
@@ -118,7 +118,7 @@
                         }
 
                         try {
-                                if (num.IndexOf ('.') != -1) {
+                                if (num.IndexOf ('.') != -1 || num.IndexOf('e') != -1 || num.IndexOf('E') != -1) {
                                         double d = Double.Parse (num, nstyles, NumberFormatInfo.InvariantInfo);
                                         result.token = Token.FLOAT64;
                                         result.val = d;
